version: "3.8"

services:
  pipedatabase:
    image: p1pe/pipe-postgres
    container_name: database-container
    ports:
      - "5434:5432"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  spring-boot-app:
    image: p1pe/pipe-crud
    container_name: app-container
    ports:
      - "8082:8080"
    environment:
      APP_DB: database
      APP_DB_PORT: 5432
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GEOCODE_KEY: ${GEOCODE_API_KEY}
      WEATHER_KEY: ${WEATHER_API_KEY}
    env_file:
      - ./env.list
    depends_on:
      - pipedatabase