spring:
  application:
    name: mycrud
  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080